# Generated by Django 5.2.1 on 2025-05-25 11:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(help_text='宠物品种的中文名称', max_length=100, verbose_name='品种名称')),
                ('name_en', models.CharField(blank=True, help_text='宠物品种的英文名称', max_length=100, verbose_name='英文名称')),
                ('pet_type', models.CharField(choices=[('cat', '猫'), ('dog', '狗'), ('rabbit', '兔子'), ('bird', '鸟'), ('fish', '鱼'), ('hamster', '仓鼠'), ('other', '其他')], max_length=20, verbose_name='宠物类型')),
                ('description', models.TextField(blank=True, help_text='该品种的特征、性格等详细描述', verbose_name='品种描述')),
                ('average_lifespan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='平均寿命（年）')),
                ('average_weight_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='平均体重下限（公斤）')),
                ('average_weight_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='平均体重上限（公斤）')),
            ],
            options={
                'verbose_name': '宠物品种',
                'verbose_name_plural': '宠物品种',
                'ordering': ['pet_type', 'name'],
                'indexes': [models.Index(fields=['pet_type', 'name'], name='pets_breed_pet_typ_84c836_idx')],
                'unique_together': {('name', 'pet_type')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=50, verbose_name='宠物姓名')),
                ('pet_type', models.CharField(choices=[('cat', '猫'), ('dog', '狗'), ('rabbit', '兔子'), ('bird', '鸟'), ('fish', '鱼'), ('hamster', '仓鼠'), ('other', '其他')], max_length=20, verbose_name='宠物类型')),
                ('custom_breed', models.CharField(blank=True, help_text='当品种列表中没有对应品种时填写', max_length=100, verbose_name='自定义品种')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('male', '雄性'), ('female', '雌性'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('is_neutered', models.CharField(choices=[('yes', '已绝育'), ('no', '未绝育'), ('unknown', '不确定')], default='unknown', max_length=10, verbose_name='绝育状态')),
                ('weight', models.FloatField(blank=True, help_text='当前体重，单位为公斤', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='体重（公斤）')),
                ('microchip_number', models.CharField(blank=True, help_text='宠物植入的微芯片编号', max_length=50, verbose_name='芯片号码')),
                ('photo', models.ImageField(blank=True, upload_to='pets/photos/', verbose_name='宠物照片')),
                ('medical_notes', models.TextField(blank=True, help_text='特殊疾病、过敏史、用药记录等重要医疗信息', verbose_name='医疗备注')),
                ('personality_notes', models.TextField(blank=True, help_text='宠物的性格特征、习惯、喜好等', verbose_name='性格备注')),
                ('is_active', models.BooleanField(default=True, help_text='宠物是否还在主人身边（未走失、未去世等）', verbose_name='是否活跃')),
                ('breed', models.ForeignKey(blank=True, help_text='如果没有对应品种，可以留空', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.breed', verbose_name='品种')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '宠物档案',
                'verbose_name_plural': '宠物档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='疫苗名称')),
                ('vaccination_date', models.DateField(verbose_name='接种日期')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次接种日期')),
                ('veterinarian', models.CharField(blank=True, max_length=100, verbose_name='接种医生')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='诊所名称')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='疫苗批号')),
                ('notes', models.TextField(blank=True, help_text='接种后反应、特殊情况等', verbose_name='备注')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '疫苗接种记录',
                'verbose_name_plural': '疫苗接种记录',
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', '-created_at'], name='pets_pet_owner_i_e3a552_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pet_type'], name='pets_pet_pet_typ_3df7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_active'], name='pets_pet_is_acti_515ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['pet', '-vaccination_date'], name='pets_vaccin_pet_id_48825d_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['next_due_date'], name='pets_vaccin_next_du_0dedb5_idx'),
        ),
    ]
