# Generated by Django 5.2.1 on 2025-05-25 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logs', models.IntegerField(default=0, verbose_name='总日志数')),
                ('last_log_date', models.DateField(blank=True, null=True, verbose_name='最后记录日期')),
                ('average_mood_score', models.FloatField(blank=True, null=True, verbose_name='平均心情评分')),
                ('average_activity_score', models.FloatField(blank=True, null=True, verbose_name='平均活跃度评分')),
                ('average_appetite_score', models.FloatField(blank=True, null=True, verbose_name='平均食欲评分')),
                ('latest_weight', models.FloatField(blank=True, null=True, verbose_name='最新体重')),
                ('weight_trend', models.CharField(choices=[('increasing', '增长'), ('decreasing', '下降'), ('stable', '稳定'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='体重趋势')),
                ('health_alerts', models.JSONField(blank=True, default=list, help_text='AI识别的健康异常提醒', verbose_name='健康提醒')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='最后分析时间')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '日志分析',
                'verbose_name_plural': '日志分析',
            },
        ),
        migrations.CreateModel(
            name='PetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('date', models.DateField(help_text='记录的日期', verbose_name='日期')),
                ('mood', models.CharField(blank=True, choices=[('very_happy', '非常开心'), ('happy', '开心'), ('normal', '正常'), ('sad', '沮丧'), ('very_sad', '非常沮丧')], max_length=20, verbose_name='心情状态')),
                ('activity_level', models.CharField(blank=True, choices=[('very_active', '非常活跃'), ('active', '活跃'), ('normal', '正常'), ('inactive', '不活跃'), ('very_inactive', '非常不活跃')], max_length=20, verbose_name='活跃程度')),
                ('appetite', models.CharField(blank=True, choices=[('excellent', '极好'), ('good', '良好'), ('normal', '正常'), ('poor', '较差'), ('very_poor', '很差')], max_length=20, verbose_name='食欲状况')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='体重（公斤）')),
                ('temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='体温（摄氏度）')),
                ('notes', models.TextField(blank=True, help_text='当日的特殊情况、行为观察等', verbose_name='备注')),
                ('photos', models.JSONField(blank=True, default=list, help_text='当日拍摄的照片文件路径列表', verbose_name='照片列表')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '宠物日志',
                'verbose_name_plural': '宠物日志',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('time', models.TimeField(verbose_name='用药时间')),
                ('medication_name', models.CharField(max_length=200, verbose_name='药物名称')),
                ('dosage', models.CharField(help_text='例如：1片、5ml、半包等', max_length=100, verbose_name='剂量')),
                ('administration_method', models.CharField(help_text='口服、注射、外用等', max_length=50, verbose_name='给药方式')),
                ('prescribed_by', models.CharField(blank=True, max_length=100, verbose_name='处方医生')),
                ('reason', models.CharField(max_length=200, verbose_name='用药原因')),
                ('side_effects', models.TextField(blank=True, help_text='用药后观察到的反应', verbose_name='副作用观察')),
                ('pet_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='logs.petlog', verbose_name='宠物日志')),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'ordering': ['pet_log__date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('log_type', models.CharField(choices=[('symptoms', '症状观察'), ('medication', '用药记录'), ('vaccination', '疫苗接种'), ('vet_visit', '就医记录'), ('grooming', '美容护理'), ('behavior_change', '行为变化')], max_length=30, verbose_name='记录类型')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='时间')),
                ('description', models.TextField(help_text='详细描述观察到的情况', verbose_name='描述')),
                ('severity', models.CharField(choices=[('normal', '正常'), ('mild', '轻微'), ('moderate', '中等'), ('severe', '严重'), ('critical', '危急')], default='normal', max_length=20, verbose_name='严重程度')),
                ('action_taken', models.TextField(blank=True, help_text='如何处理该情况', verbose_name='采取的行动')),
                ('pet_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='logs.petlog', verbose_name='宠物日志')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['pet_log__date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('time', models.TimeField(verbose_name='喂食时间')),
                ('food_type', models.CharField(help_text='主粮、零食、罐头等', max_length=100, verbose_name='食物类型')),
                ('food_brand', models.CharField(blank=True, max_length=100, verbose_name='食物品牌')),
                ('amount', models.CharField(help_text='例如：一杯、50克、半罐等', max_length=50, verbose_name='食量')),
                ('eaten_percentage', models.IntegerField(blank=True, help_text='宠物实际吃掉的比例', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进食比例（%）')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('pet_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='logs.petlog', verbose_name='宠物日志')),
            ],
            options={
                'verbose_name': '喂食记录',
                'verbose_name_plural': '喂食记录',
                'ordering': ['pet_log__date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('exercise_type', models.CharField(help_text='散步、跑步、游戏、训练等', max_length=50, verbose_name='运动类型')),
                ('intensity', models.CharField(choices=[('low', '低强度'), ('medium', '中强度'), ('high', '高强度')], default='medium', max_length=20, verbose_name='运动强度')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='运动地点')),
                ('distance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='距离（公里）')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('pet_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='logs.petlog', verbose_name='宠物日志')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'ordering': ['pet_log__date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='petlog',
            index=models.Index(fields=['pet', '-date'], name='logs_petlog_pet_id_7ce6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='petlog',
            index=models.Index(fields=['date'], name='logs_petlog_date_2a4b6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='petlog',
            unique_together={('pet', 'date')},
        ),
    ]
