# Generated by Django 5.2.1 on 2025-05-26 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlog',
            name='age_at_record',
            field=models.IntegerField(blank=True, help_text='记录时宠物的实际年龄，单位：天', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='记录时年龄（天）'),
        ),
        migrations.AddField(
            model_name='petlog',
            name='daily_events',
            field=models.TextField(blank=True, help_text='记录当日发生的特殊事件、行为变化、就医情况等', verbose_name='当日事件'),
        ),
        migrations.AddField(
            model_name='petlog',
            name='food_intake',
            field=models.FloatField(blank=True, help_text='当日总食物摄入量，包括主粮和零食', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='食物摄入量（克）'),
        ),
        migrations.AddField(
            model_name='petlog',
            name='length',
            field=models.FloatField(blank=True, help_text='从鼻尖到尾尖的长度，单位：厘米', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='身长（厘米）'),
        ),
        migrations.AddField(
            model_name='petlog',
            name='water_intake',
            field=models.FloatField(blank=True, help_text='当日总饮水量', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='饮水量（毫升）'),
        ),
        migrations.AlterField(
            model_name='petlog',
            name='date',
            field=models.DateField(help_text='记录的日期，每个宠物每天只能有一条记录', verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='petlog',
            name='notes',
            field=models.TextField(blank=True, help_text='其他需要记录的信息', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='petlog',
            name='temperature',
            field=models.FloatField(blank=True, help_text='体温，正常范围因宠物类型而异', null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='体温（摄氏度）'),
        ),
        migrations.AlterField(
            model_name='petlog',
            name='weight',
            field=models.FloatField(blank=True, help_text='宠物当日体重，单位：公斤', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500.0)], verbose_name='体重（公斤）'),
        ),
        migrations.AddIndex(
            model_name='petlog',
            index=models.Index(fields=['pet', 'weight'], name='logs_petlog_pet_id_3c36b6_idx'),
        ),
    ]
