# Generated by Django 5.2.1 on 2025-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consultationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhistory',
            name='consult_type',
            field=models.CharField(choices=[('feeding', '日常饲养建议'), ('vaccine', '疫苗接种建议'), ('health', '健康与行为建议'), ('emergency', '紧急情况指引'), ('general', '综合咨询')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationhistory',
            name='specific_question',
            field=models.TextField(blank=True, help_text='具体问题描述'),
        ),
    ]
