# Generated by Django 5.2.1 on 2025-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_consultationhistory_consult_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhistory',
            name='emergency_symptoms',
            field=models.TextField(blank=True, help_text='紧急症状描述'),
        ),
    ]
