# Generated by Django 5.2.1 on 2025-05-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_consultationhistory_emergency_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhistory',
            name='gender',
            field=models.CharField(choices=[('male', '雄性'), ('female', '雌性'), ('unknown', '未知')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='consultationhistory',
            name='is_neutered',
            field=models.CharField(blank=True, choices=[('yes', '已绝育'), ('no', '未绝育'), ('unknown', '不确定')], default='unknown', max_length=10),
        ),
        migrations.AddIndex(
            model_name='consultationhistory',
            index=models.Index(fields=['user', '-created_at'], name='accounts_co_user_id_7d226f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationhistory',
            index=models.Index(fields=['created_at'], name='accounts_co_created_f6fc62_idx'),
        ),
    ]
