# Generated by Django 5.2.1 on 2025-05-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_consultationhistory_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationHistory',
        ),
    ]
