# Generated by Django 5.2.1 on 2025-05-25 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='模板标题')),
                ('consult_type', models.CharField(choices=[('feeding', '日常饲养建议'), ('vaccine', '疫苗接种建议'), ('health', '健康与行为建议'), ('emergency', '紧急情况指引'), ('general', '综合咨询')], max_length=20, verbose_name='咨询类型')),
                ('pet_type', models.CharField(blank=True, help_text='留空表示适用所有宠物类型', max_length=20, verbose_name='适用宠物类型')),
                ('template_content', models.TextField(help_text='问题描述的模板文本', verbose_name='模板内容')),
                ('suggested_response', models.TextField(blank=True, help_text='针对此类问题的标准回复模板', verbose_name='建议回复')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '咨询模板',
                'verbose_name_plural': '咨询模板',
                'ordering': ['-usage_count', 'title'],
                'indexes': [models.Index(fields=['consult_type', 'is_active'], name='consultatio_consult_c51ed4_idx'), models.Index(fields=['pet_type'], name='consultatio_pet_typ_f507ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('consult_type', models.CharField(choices=[('feeding', '日常饲养建议'), ('vaccine', '疫苗接种建议'), ('health', '健康与行为建议'), ('emergency', '紧急情况指引'), ('general', '综合咨询')], default='general', max_length=20, verbose_name='咨询类型')),
                ('pet_type', models.CharField(blank=True, help_text='当没有关联宠物档案时填写', max_length=20, verbose_name='宠物类型')),
                ('breed', models.CharField(blank=True, help_text='当没有关联宠物档案时填写', max_length=100, verbose_name='品种')),
                ('age', models.IntegerField(blank=True, help_text='当没有关联宠物档案时填写，单位为月', null=True, verbose_name='年龄（月）')),
                ('weight', models.FloatField(blank=True, help_text='当没有关联宠物档案时填写', null=True, verbose_name='体重（公斤）')),
                ('gender', models.CharField(blank=True, choices=[('male', '雄性'), ('female', '雌性'), ('unknown', '未知')], default='unknown', help_text='当没有关联宠物档案时填写', max_length=10, verbose_name='性别')),
                ('is_neutered', models.CharField(blank=True, choices=[('yes', '已绝育'), ('no', '未绝育'), ('unknown', '不确定')], default='unknown', help_text='当没有关联宠物档案时填写', max_length=10, verbose_name='绝育状态')),
                ('specific_question', models.TextField(blank=True, help_text='详细描述您想咨询的问题', verbose_name='具体问题描述')),
                ('emergency_symptoms', models.TextField(blank=True, help_text='如果是紧急情况，请详细描述症状', verbose_name='紧急症状描述')),
                ('additional_info', models.TextField(blank=True, help_text='其他相关信息，如环境、饮食、行为变化等', verbose_name='补充信息')),
                ('advice', models.TextField(help_text='AI生成的建议和回复', verbose_name='AI建议')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI回复的置信度评分（0-1）', null=True, verbose_name='置信度分数')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], help_text='用户对AI建议的评分（1-5星）', null=True, verbose_name='用户评分')),
                ('user_feedback', models.TextField(blank=True, help_text='用户对AI建议的文字反馈', verbose_name='用户反馈')),
                ('session_id', models.CharField(blank=True, help_text='用于关联同一次对话的多轮咨询', max_length=100, verbose_name='会话ID')),
                ('ai_model_version', models.CharField(blank=True, help_text='生成回复的AI模型版本', max_length=50, verbose_name='AI模型版本')),
                ('processing_time', models.FloatField(blank=True, help_text='AI处理请求所用的时间', null=True, verbose_name='处理时间（秒）')),
                ('pet', models.ForeignKey(blank=True, help_text='如果咨询是针对特定宠物的，可以关联宠物档案', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet', verbose_name='关联宠物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI咨询历史',
                'verbose_name_plural': 'AI咨询历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='consultatio_user_id_d70cc6_idx'), models.Index(fields=['created_at'], name='consultatio_created_7f811c_idx'), models.Index(fields=['consult_type'], name='consultatio_consult_a04ada_idx'), models.Index(fields=['session_id'], name='consultatio_session_745d75_idx'), models.Index(fields=['pet'], name='consultatio_pet_id_c975f5_idx')],
            },
        ),
    ]
